name: http_api_generator
description: A package that help you to generate Http Restful Api by annotation.
version: 1.1.0
homepage: https://github.com/xiaozhizhong/http_api

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: ^5.0.0
  build: ^2.3.1
  code_builder: ^4.4.0
  meta: ^1.8.0
  source_gen: ^1.2.6
  dart_style: ^2.2.4
  built_collection: ^5.1.1
dev_dependencies:
  build_runner: ^2.3.2